-- Create player records for all registrations that don't have a player_id
-- This handles legacy data where registrations were created without player records

-- Insert new players for registrations with NULL player_id
-- Use the full_name from registration as the player name
INSERT INTO players (name, betting_code)
SELECT DISTINCT
  r.full_name,
  NULL  -- betting_code will be auto-generated by the trigger
FROM registrations r
WHERE r.player_id IS NULL
  AND r.full_name IS NOT NULL
  AND r.full_name != ''
  AND NOT EXISTS (
    -- Don't create duplicate players if one with same name already exists
    SELECT 1 FROM players p WHERE LOWER(TRIM(p.name)) = LOWER(TRIM(r.full_name))
  );

-- Update registrations to link them to their player records
-- Match by name (case-insensitive, trimmed)
UPDATE registrations r
SET player_id = p.id
FROM players p
WHERE r.player_id IS NULL
  AND LOWER(TRIM(r.full_name)) = LOWER(TRIM(p.name));

-- Report on the results
SELECT
  COUNT(*) FILTER (WHERE player_id IS NULL) as still_missing_player_id,
  COUNT(*) FILTER (WHERE player_id IS NOT NULL) as has_player_id,
  COUNT(*) as total_registrations
FROM registrations;
